// Author Alexander Rass
#include <bits/stdc++.h>
using namespace std;
// USAGE:
// just call the program without any parameter
// the input is parsed by string (not by line)
// first line input file
// second line output file
// third line gnuplot data file (which should be generated by this program)

const int MAXN = 1024;
long double x[MAXN],y[MAXN];
int main(){
    string temp_outputfile, inputfilename, outputfilename;
    cin >> inputfilename >> outputfilename >> temp_outputfile;
    ifstream inputfile(inputfilename);
    ifstream outputfile(outputfilename);
    ofstream gnuplotdatafile(temp_outputfile);
    int N;
    inputfile >> N;
    for(int i = 1; i <= N; i++){
        outputfile >> x[i] >> y[i];
    }
    for(int i = 1; i < N; i++){
        int a,b;
        inputfile >> a >> b;
        gnuplotdatafile << setprecision(15);
        gnuplotdatafile << x[a] << " " << y[a] << " "<< x[b] << " "<< y[b] << endl;
    }
	return 0;
}
